[2023-09-23T22:52:30.714+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_dag.test_db manual__2023-09-23T22:52:21.234679+00:00 [queued]>
[2023-09-23T22:52:30.723+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_dag.test_db manual__2023-09-23T22:52:21.234679+00:00 [queued]>
[2023-09-23T22:52:30.724+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-23T22:52:30.751+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): test_db> on 2023-09-23 22:52:21.234679+00:00
[2023-09-23T22:52:30.754+0000] {standard_task_runner.py:57} INFO - Started process 21 to run task
[2023-09-23T22:52:30.756+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'test_dag', 'test_db', 'manual__2023-09-23T22:52:21.234679+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmp36aabxjy']
[2023-09-23T22:52:30.757+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask test_db
[2023-09-23T22:52:30.778+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-09-23T22:52:30.814+0000] {task_command.py:415} INFO - Running <TaskInstance: test_dag.test_db manual__2023-09-23T22:52:21.234679+00:00 [running]> on host test-dag-test-db-yrc90nxy
[2023-09-23T22:52:30.888+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/kube_config.py:57 DeprecationWarning: The namespace option in [kubernetes] has been moved to the namespace option in [kubernetes_executor] - the old setting has been used, but please update your config.
[2023-09-23T22:52:30.890+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/kube_config.py:71 DeprecationWarning: The namespace option in [kubernetes] has been moved to the namespace option in [kubernetes_executor] - the old setting has been used, but please update your config.
[2023-09-23T22:52:30.890+0000] {pod_generator.py:539} WARNING - Model file /opt/airflow/executor-pod-template.yml does not exist
[2023-09-23T22:52:30.938+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='test_dag' AIRFLOW_CTX_TASK_ID='test_db' AIRFLOW_CTX_EXECUTION_DATE='2023-09-23T22:52:21.234679+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-23T22:52:21.234679+00:00'
[2023-09-23T22:52:30.982+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 633, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: No database selected

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_dag.py", line 27, in test_db
    curs.execute("SELECT * FROM predictions LIMIT 1")
  File "/home/airflow/.local/lib/python3.8/site-packages/mysql/connector/cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "/home/airflow/.local/lib/python3.8/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 86, in wrapper
    result = method(cnx, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 641, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.ProgrammingError: 1046 (3D000): No database selected
[2023-09-23T22:52:30.992+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=test_dag, task_id=test_db, execution_date=20230923T225221, start_date=20230923T225230, end_date=20230923T225230
[2023-09-23T22:52:31.014+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 11 for task test_db (1046 (3D000): No database selected; 21)
[2023-09-23T22:52:31.049+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-23T22:52:31.079+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
