[2023-09-20 10:41:11,524] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: check_precision_dag.check_precision_task 2023-09-20T10:41:09.528990+00:00 [queued]>
[2023-09-20 10:41:11,533] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: check_precision_dag.check_precision_task 2023-09-20T10:41:09.528990+00:00 [queued]>
[2023-09-20 10:41:11,534] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-09-20 10:41:11,535] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2023-09-20 10:41:11,535] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-09-20 10:41:11,547] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): check_precision_task> on 2023-09-20T10:41:09.528990+00:00
[2023-09-20 10:41:11,550] {standard_task_runner.py:52} INFO - Started process 300 to run task
[2023-09-20 10:41:11,553] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'check_precision_dag', 'check_precision_task', '2023-09-20T10:41:09.528990+00:00', '--job-id', '21', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/check_precision_dag.py', '--cfg-path', '/tmp/tmpbxj95mcc', '--error-file', '/tmp/tmpyw7vm76_']
[2023-09-20 10:41:11,554] {standard_task_runner.py:77} INFO - Job 21: Subtask check_precision_task
[2023-09-20 10:41:11,589] {logging_mixin.py:104} INFO - Running <TaskInstance: check_precision_dag.check_precision_task 2023-09-20T10:41:09.528990+00:00 [running]> on host 8cd7e31f5946
[2023-09-20 10:41:11,630] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=check_precision_dag
AIRFLOW_CTX_TASK_ID=check_precision_task
AIRFLOW_CTX_EXECUTION_DATE=2023-09-20T10:41:09.528990+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-20T10:41:09.528990+00:00
[2023-09-20 10:41:11,792] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/check_precision_dag.py", line 55, in get_result
    print('erreur moyenne calculee : ' + result + '%')
TypeError: must be str, not numpy.float64
[2023-09-20 10:41:11,798] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=check_precision_dag, task_id=check_precision_task, execution_date=20230920T104109, start_date=20230920T104111, end_date=20230920T104111
[2023-09-20 10:41:11,845] {local_task_job.py:151} INFO - Task exited with return code 1
